### ISSUE TITLE
Implement CREATE and DOES>

### ISSUE THREAD

**Issue by tgvaughan** [tgvaughan/forth.jl#2]
JonesForth has a CREATE word, but this is mislabeled.

**Comment by larsbrinkhoff** [comment]
Forths written in assembly langage can use some clever tricks with `call` instructions.  But high-level languages can't do this.  The solution used in Gforth, and which I also use in my own forth, is to add one more cell to the word header.

**Comment by tgvaughan** [comment]
Hi @larsbrinkhoff, according to "moving forth", this is the trick employed by figforth too.  I was actually going to use the approach of having unique "assembly" for for each defining word defined using `DOES>`.   I can do this quite easily in Julia due to its extensive support for meta-programming.

**Comment by larsbrinkhoff** [comment]
Cool, I'd like to see it when you're done.
