### ISSUE TITLE
Clean up outer interpreter

### ISSUE THREAD

**Issue by tgvaughan** [tgvaughan/forth.jl#3]
Currently the structure is very similar to JonesForth, with some hacks (such as defining words with control characters as names) to get "ok" printed in the right places.  Much of this mess can be avoided simply by using the standard hierarchy of words to implement the outer interpreter.

For instance, JonesForth has QUIT loop over calls to INTERPRET.  Each of these calls use WORD to take a single word from the input stream and execute/compile it.  WORD calls KEY, which reads single characters from STDIN and adds them to the TIB, updating >IN and #TIB along the way.

What _should_ happen is this:

QUIT should loop over calls to QUERY and INTERPRET.  QUERY reads a whole line from STDIN using the general purpose word EXPECT.  QUERY is responsible for filling the TIB, setting #TIB and initializing >IN.  INTERPRET is itself a loop which executes/compiles every word in the TIB.  It does this via successive calls to WORD, which simply scans through the  TIB and returns a substring bracketed by a chosen delimiter (in the case of INTERPRET this is BL).

This way you don't need ugly hacks, because QUIT can easily display a message if INTERPRET succeeded (and the STATE is right).

**Comment by larsbrinkhoff** [comment]
Perhaps you can use this for inspiration:

    create interpreters  ' execute , ' number , ' execute ,
    : interpret-xt   1+ cells  interpreters + @ execute ;
    : [   0 state !  ['] execute interpreters !  ; immediate
    : ]   1 state !  ['] compile, interpreters ! ;

    : parsed ( a u -- ) find-name interpret-xt ;
    : interpret   begin parse-name dup while parsed repeat 2drop ;
    : interpreting   begin refill while interpret ?prompt repeat ;
    : quit   rp0 rp!  postpone [  terminal-input interpreting  bye ;

As you may be able to guess, `find-name` and `parse-name` are like `FIND` and `WORD`, but accept `a u` strings.  `?prompt` prints `ok` only when interpreting terminal input.

**Comment by tgvaughan** [comment]
Sweet, thanks!   I've actually got a non-primitive interpret implemented (much less clean than yours), but it's causing some strange bugs to appear in compiler words (specifically my massively too-complex implementations of ?DO and LOOP+), which I'll sort out when I have time.  (This is all going on in the interpret branch.)

One (perhaps) peculiar thing about jonesforth is that control flow words aren't defined until after the interpreter/compiler is in place.  I kinda like this, because it means that much more of the core is defined in a pure forth library file.  I've tried to keep with (and even extend) this idea in my implementation.   The one drawback is that I only have primitive branching words at the time the interpreter is being defined, so at the moment it's peppered with relative jumps, making it harder to debug.

Anyway, the code (especially in the interpret branch) is pretty embarrassing at the moment.  I'm debugging, so please excuse the messiness!
